import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(__file__), '..', '..', '.env'))

DATABASE_URL = os.getenv("DATABASE_URL",
    f"postgresql://garden_user:{os.getenv('DB_PASSWORD')}@localhost:5432/garden")

engine = create_engine(DATABASE_URL)

def get_zone_id(session, code):
    result = session.execute(text("SELECT id FROM zones WHERE code = :code"), {"code": code})
    row = result.fetchone()
    return row[0] if row else None

def seed_plants(session):
    plants = [
        # ── PATIO COVERED ─────────────────────────────────────────────
        dict(code="P1",  common_name="Jasmin étoilé panaché",        latin_name="Trachelospermum jasminoides Variegatum",   zone_code="patio_covered",      container="pot",                  status="Struggling", status_notes="Cochenilles (faible niveau) + fumagine. Traitement savon noir 08/10.04.2026. Nouvelles pousses encourageantes.",  acquired_from="jardins-du-monde",       acquired_date="2022-08-09", grid_col=14, grid_row=1, grid_slot=1),
        dict(code="P2",  common_name="Jasmin étoilé",                latin_name="Trachelospermum jasminoides",              zone_code="patio_covered",      container="pot",                  status="Struggling", status_notes="Cochenilles (faible niveau). Traitement savon noir 08/10.04.2026. Nouvelles pousses + pousse montante.",            acquired_from="jardins-du-monde",       acquired_date="2022-08-09", grid_col=14, grid_row=3, grid_slot=1),
        dict(code="P3",  common_name="Azalée du Japon rouge",        latin_name="Azalea japonica red",                     zone_code="patio_covered",      container="pot",                  status="Struggling", status_notes="Rempotage 10.04.2026 — rootball peu développé (pH suspect). Chenilles retirées. Cochenilles traitées. Soufre à ajouter.", acquired_from=None,                    acquired_date=None,         grid_col=15, grid_row=0, grid_slot=1),
        dict(code="P4",  common_name="Heuchère 'Caramel'®",          latin_name="Heuchera 'Caramel'®",                     zone_code="patio_shelf_1",      container="pot",                  status="Thriving",      status_notes="Divisée (voir P4b).",                                                                                               acquired_from=None,                    acquired_date=None,         grid_col=15, grid_row=1, grid_slot=1),

        # ── PATIO UNCOVERED ───────────────────────────────────────────
        dict(code="P5",  common_name="Misère",                       latin_name="Tradescantia fluminensis",                zone_code="patio_uncovered",    container="pot suspendu",         status="Thriving",      status_notes="Nettoyé + rempoté 12.04.2026. Déplacé rambarde basse droite. Pot cassé remplacé.",                                  acquired_from=None,                    acquired_date="2018-01-01", grid_col=16, grid_row=0, grid_slot=1),
        dict(code="P6",  common_name="Laurier rose",                 latin_name="Nerium oleander",                         zone_code="patio_uncovered",    container="grand pot ~80cm",      status="Thriving",      status_notes="A perdu de la densité. Toxique.",                                                                                    acquired_from=None,                    acquired_date=None,         grid_col=16, grid_row=4, grid_slot=1),
        dict(code="P7",  common_name="Olivier",                      latin_name="Olea europaea",                           zone_code="patio_uncovered",    container="grand pot bleu",       status="Struggling", status_notes="Trous ronds sur feuilles. Nouvelles pousses visibles 08.04.2026 — prudent optimisme.",                              acquired_from=None,                    acquired_date=None,         grid_col=14, grid_row=4, grid_slot=1),
        dict(code="P27", common_name="Pesse d'eau (rejet)",          latin_name="Hippuris vulgaris",                       zone_code="patio_uncovered",    container="pot suspendu",         status="Thriving",      status_notes="Hiver difficile, repart.",                                                                                           acquired_from=None,                    acquired_date=None,         grid_col=16, grid_row=2, grid_slot=1),

        # ── PATIO SHELF 1 ─────────────────────────────────────────────
        dict(code="P31", common_name="Hosta Frances Williams",       latin_name="Hosta sieboldiana 'Elegans'",             zone_code="patio_shelf_1",      container="pot",                  status="Thriving",      status_notes="Repousse mars 2026. Rempotage à planifier.",                                                                         acquired_from=None,                    acquired_date="2023-07-31", grid_col=15, grid_row=0, grid_slot=1),
        dict(code="P32", common_name="Hosta Sunset",                 latin_name="Hosta 'Sunset'",                          zone_code="patio_shelf_1",      container="pot",                  status="Thriving",      status_notes="Repousse mars 2026. Rempotage à planifier.",                                                                         acquired_from=None,                    acquired_date="2022-07-25", grid_col=15, grid_row=2, grid_slot=1),
        dict(code="P33", common_name="Iris (rejet étang)",           latin_name="Iris sp.",                                zone_code="patio_shelf_1",      container="pot argile",           status="Thriving",      status_notes="Repousse mars 2026 — inattendue après hivernage. Variété à identifier à la floraison.",                              acquired_from=None,                    acquired_date=None,         grid_col=15, grid_row=3, grid_slot=1),
        dict(code="P35", common_name="Salvia Icterina",              latin_name="Salvia officinalis 'Icterina'",           zone_code="patio_shelf_1",      container="pot terracotta",       status="Thriving",      status_notes="Planté 10.04.2026. Terre bordure + sable de rivière. Soucoupe à vider régulièrement.",                              acquired_from="Brico",                 acquired_date="2026-03-26", grid_col=15, grid_row=4, grid_slot=1),
        dict(code="P41", common_name="Verbena citriodora",           latin_name="Aloysia citrodora",                       zone_code="patio_shelf_1",      container="pot jaune",            status="Thriving",      status_notes="Acheté Aldi 11.04.2026. Rempoté 12.04.2026. Peu rustique — hivernage à prévoir.",                                    acquired_from="Aldi Evere",            acquired_date="2026-04-11", grid_col=16, grid_row=0, grid_slot=3),
        dict(code="P46", common_name="Pittosporum 'Tom Thumb'",      latin_name="Pittosporum tenuifolium 'Tom Thumb'",     zone_code="patio_shelf_1",      container="pot",                  status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Rempoté, étagère 1 niveau 2 (soleil direct partiel). Emplacement définitif à décider.",     acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=16, grid_row=0, grid_slot=4),
        dict(code="P47", common_name="Viburnum tinus",               latin_name="Viburnum tinus",                          zone_code="patio_shelf_1",      container="pot",                  status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Rempoté, étagère 1 niveau supérieur. Futur : zone morte arrière bordure droite.",           acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=16, grid_row=0, grid_slot=5),

        # ── PATIO SHELF 2 ─────────────────────────────────────────────
        dict(code="P29", common_name="Papyrus",                      latin_name="Cyperus papyrus",                         zone_code="patio_shelf_2",      container="pot",                  status="Thriving",      status_notes="Nouvelles pousses actives. Tiges mortes retirées 08.04.2026. Rempotage dans pot plus grand à faire.",               acquired_from=None,                    acquired_date=None,         grid_col=17, grid_row=3, grid_slot=1),
        dict(code="P30", common_name="Heuchère 'Fire Chief'",        latin_name="Heuchera 'Fire Chief'",                   zone_code="patio_shelf_2",      container="petit pot",            status="Struggling", status_notes="2 feuilles — état critique.",                                                                                        acquired_from=None,                    acquired_date=None,         grid_col=16, grid_row=0, grid_slot=1),
        dict(code="P36", common_name="Grande pervenche 'Variegata'", latin_name="Vinca major 'Variegata'",                 zone_code="patio_shelf_2",      container="pot terracotta",       status="Struggling", status_notes="Reprise inattendue après hivernage waterloggé. Nettoyé + rempoté 12.04.2026. Sous observation.",                   acquired_from="jardindupicvert",       acquired_date="2023-04-13", grid_col=17, grid_row=1, grid_slot=1),

        # ── ENTRY / PAVED ZONE LEFT ───────────────────────────────────
        dict(code="P8",  common_name="Forsythia",                    latin_name="Forsythia intermedia Spectabilis",        zone_code="entry",              container="pot",                  status="Thriving",      status_notes="Taille sévère 29.03.2026. Nouvelles pousses confirmées 08.04.2026.",                                                  acquired_from="JardinPourVous",        acquired_date="2022-07-18", grid_col=13, grid_row=2, grid_slot=1),
        dict(code="P9",  common_name="Choisya",                      latin_name="Choisya ternata",                         zone_code="entry",              container="pot",                  status="Thriving",      status_notes="Floraison en cours 08.04.2026. Déséquilibré — à tailler légèrement.",                                               acquired_from="jardindupicvert",       acquired_date="2023-04-13", grid_col=13, grid_row=4, grid_slot=1),
        dict(code="P37", common_name="Rosier sp.",                   latin_name="Rosa sp.",                                zone_code="entry",              container="pot bleu",             status="Struggling", status_notes="Trouvé abandonné au trottoir 12.04.2026. Plant stressé, nouvelles pousses visibles. Variété inconnue.",            acquired_from="Trouvé trottoir",       acquired_date="2026-04-12", grid_col=10, grid_row=0, grid_slot=1),
        dict(code="P38", common_name="Menthe chocolat",              latin_name="Mentha × piperita 'Chocolate'",           zone_code="entry",              container="pot plastique semi-enterré", status="Thriving", status_notes="Reprise spontanée après hivernage. Nettoyé + terre fraîche 12.04.2026.",                                          acquired_from="Brico",                 acquired_date="2023-05-12", grid_col=12, grid_row=6, grid_slot=1),
        dict(code="P39", common_name="Menthe Orangenminze",          latin_name="Mentha × piperita 'Orange'",              zone_code="entry",              container="pot plastique semi-enterré", status="Struggling", status_notes="Reprise très timide. Nettoyé + terre fraîche 12.04.2026.",                                                 acquired_from="Pépinière de Boisfort", acquired_date="2022-07-29", grid_col=12, grid_row=7, grid_slot=1),
        dict(code="P40", common_name="Menthe poivrée",               latin_name="Mentha × piperita",                       zone_code="entry",              container="pot plastique semi-enterré", status="Thriving", status_notes="Acheté Aldi 11.04.2026. Rempotée pot plus grand 12.04.2026.",                                                    acquired_from="Aldi Evere",            acquired_date="2026-04-11", grid_col=12, grid_row=8, grid_slot=1),

        # ── RETAINING WALL ────────────────────────────────────────────
        dict(code="P43", common_name="Armeria armada white",         latin_name="Armeria maritima 'Armada White'",         zone_code="retaining_wall",     container="pot suspendu",         status="Thriving",      status_notes="Acheté Carrefour 12.04.2026. Jardinière rambarde avec P50 Munstead — substrat sableux prêt.",                       acquired_from="Carrefour Evere",       acquired_date="2026-04-12", grid_col=12, grid_row=3, grid_slot=1),
        dict(code="P49", common_name="Lavande Hidcote #2",           latin_name="Lavandula angustifolia 'Hidcote'",        zone_code="retaining_wall",     container="pot suspendu",         status="Thriving",      status_notes="Bakker. Planté 15.04.2026 dans pot suspendu près de l'escalier. Substrat allégé sable + graviers.",                acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=12, grid_row=2, grid_slot=1),
        dict(code="P50", common_name="Lavande Munstead",             latin_name="Lavandula angustifolia 'Munstead'",       zone_code="retaining_wall",     container="pot suspendu",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Grand plant (2L). Plant ancre jardinière rambarde avec P43 Armeria.",                     acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=12, grid_row=4, grid_slot=1),

        # ── LEFT BORDER FRONT ─────────────────────────────────────────
        dict(code="P10", common_name="Thym orange",                  latin_name="Thymus fragrantissimus",                  zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Thriving.",                                                                                                          acquired_from="Pépinière de Boisfort", acquired_date="2022-07-29", grid_col=3,  grid_row=1, grid_slot=1),
        dict(code="P11", common_name="Sarriette des montagnes",      latin_name="Satureja montana",                        zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Thriving.",                                                                                                          acquired_from=None,                    acquired_date=None,         grid_col=4,  grid_row=1, grid_slot=1),
        dict(code="P12", common_name="Romarin",                      latin_name="Salvia rosmarinus",                       zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Thriving.",                                                                                                          acquired_from="Colruyt",               acquired_date="2023-04-01", grid_col=5,  grid_row=1, grid_slot=1),
        dict(code="P34", common_name="Salvia Icterina",              latin_name="Salvia officinalis 'Icterina'",           zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Planté 10.04.2026 près du thym. Terre bordure + sable de rivière + coquilles d'œufs + marc de café.",             acquired_from="Brico",                 acquired_date="2026-03-26", grid_col=6,  grid_row=1, grid_slot=1),
        dict(code="P45", common_name="Curry plant",                  latin_name="Helichrysum italicum subsp. serotinum",   zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Petit plant. Coin aromatiques près du thym et de la sauge.",                             acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=7,  grid_row=1, grid_slot=1),
        dict(code="P48", common_name="Lavande Hidcote #1",           latin_name="Lavandula angustifolia 'Hidcote'",        zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Destination bordure gauche, pleine terre.",                                               acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=2,  grid_row=1, grid_slot=1),
        dict(code="P51", common_name="Nepeta Walker's Low",          latin_name="Nepeta × faassenii 'Walker's Low'",       zone_code="left_border_front",  container="pleine terre",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Zone aromatiques bordure gauche.",                                                         acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=8,  grid_row=1, grid_slot=1),

        # ── LEFT BORDER BACK ──────────────────────────────────────────
        dict(code="P13", common_name="Fusain jaune",                 latin_name="Euonymus japonicus (var. ?)",             zone_code="left_border_back",   container="pleine terre",         status="Thriving",      status_notes="Compact, croissance très lente. Variété exacte à identifier.",                                                       acquired_from=None,                    acquired_date=None,         grid_col=9,  grid_row=1, grid_slot=1),
        dict(code="P14", common_name="Photinia 'Little Fenna'",      latin_name="Photinia fraseri 'Little Fenna'",         zone_code="left_border_back",   container="pleine terre",         status="Struggling", status_notes="Fragile, ~20cm, taches brunes. Traitement neem 03.04.2026.",                                                        acquired_from="JardinPourVous",        acquired_date="2022-07-18", grid_col=10, grid_row=1, grid_slot=1),
        dict(code="P15", common_name="Red Robin #1",                 latin_name="Photinia fraseri Red Robin",              zone_code="left_border_back",   container="pleine terre",         status="Struggling", status_notes="Taille semi-sévère 20.03. Traitement neem 03.04. Pas de nouvelles pousses visibles au 08.04.",                     acquired_from="JardinPourVous",        acquired_date="2023-03-21", grid_col=11, grid_row=1, grid_slot=1),
        dict(code="P16", common_name="Red Robin #2",                 latin_name="Photinia fraseri Red Robin",              zone_code="left_border_back",   container="pleine terre",         status="Struggling", status_notes="Taille semi-sévère 20.03. Traitement neem 03.04. Pas de nouvelles pousses visibles au 08.04.",                     acquired_from="JardinPourVous",        acquired_date="2023-03-21", grid_col=11, grid_row=1, grid_slot=1),
        dict(code="P52", common_name="Nepeta Grog",                  latin_name="Nepeta racemosa 'Grog'",                  zone_code="left_border_back",   container="pleine terre",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. Destination provisoire bordure gauche zone sauvage — à réévaluer.",                       acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=11, grid_row=1, grid_slot=3),

        # ── RIGHT BORDER FRONT ────────────────────────────────────────
        dict(code="P22", common_name="Troène doré",                  latin_name="Ligustrum ovalifolium Aureum",            zone_code="right_border_front", container="pleine terre",         status="Thriving",      status_notes="Taille légère 03.04.2026.",                                                                                          acquired_from="JardinPourVous",        acquired_date="2023-03-21", grid_col=3,  grid_row=8, grid_slot=1),
        dict(code="P21", common_name="Red Robin #4",                 latin_name="Photinia fraseri Red Robin",              zone_code="right_border_front", container="pleine terre",         status="Struggling", status_notes="Taille très sévère 20.03. Entomosporium confirmé. Traitement neem 03.04.2026. Fourmi observée 08.04 — surveiller pucerons.", acquired_from="JardinPourVous",   acquired_date="2023-03-21", grid_col=5,  grid_row=8, grid_slot=1),
        dict(code="P44", common_name="Ilex crenata Fastigiata",      latin_name="Ilex crenata 'Fastigiata'",               zone_code="right_border_front", container="pleine terre",         status="Thriving",      status_notes="Bakker. Reçu 15.04.2026. ~50cm, forme colonnaire. Entre P22 et P23. Plantation prévue ce weekend.",                acquired_from="Bakker",                acquired_date="2026-04-15", grid_col=4,  grid_row=8, grid_slot=1),

        # ── RIGHT BORDER BACK ─────────────────────────────────────────
        dict(code="P23", common_name="Fusain Emerald Gaiety",        latin_name="Euonymus japonicus 'Emerald Gaiety'",     zone_code="right_border_back",  container="pleine terre",         status="Thriving",      status_notes="Exceptionnel — quasi 1m, très dense.",                                                                               acquired_from="Brico",                 acquired_date="2022-07-09", grid_col=6,  grid_row=8, grid_slot=1),
        dict(code="P24", common_name="Camélia Mary Williams",        latin_name="Camellia reticulata Mary Williams",       zone_code="right_border_back",  container="pleine terre",         status="Struggling", status_notes="Adaptation difficile. Boutons tombent avant éclosion chaque année. pH insuffisant probable.",                       acquired_from="jardins-du-monde",      acquired_date="2022-08-09", grid_col=7,  grid_row=8, grid_slot=1),
        dict(code="P25", common_name="Pieris Forest Flame",          latin_name="Pieris japonica Forest Flame",            zone_code="right_border_back",  container="pleine terre",         status="Struggling", status_notes="Mourant. Tuteuré 08.04.2026 — légère amélioration. Quelques nouvelles pousses. pH test en attente.",                acquired_from="JardinPourVous",        acquired_date="2023-03-21", grid_col=8,  grid_row=8, grid_slot=1),
        dict(code="P26", common_name="Red Robin #5",                 latin_name="Photinia fraseri Red Robin",              zone_code="right_border_back",  container="pleine terre",         status="Thriving",      status_notes="OK pour la pleine ombre.",                                                                                           acquired_from="JardinPourVous",        acquired_date="2023-03-21", grid_col=9,  grid_row=8, grid_slot=1),
        dict(code="P20", common_name="Andromède Blue Lagoon",        latin_name="Andromeda polifolia Blue Lagoon",         zone_code="right_border_back",  container="pleine terre",         status="Thriving",      status_notes="OK — lente (1 survivante sur 3). Acidophile.",                                                                       acquired_from="JardinPourVous",        acquired_date="2022-07-22", grid_col=10, grid_row=8, grid_slot=1),
        dict(code="P4b", common_name="Heuchère 'Caramel'® (division)", latin_name="Heuchera 'Caramel'®",                  zone_code="right_border_back",  container="pot",                  status="Thriving",      status_notes="Thriving — nouvelles feuilles rose/violet vif. Bon emplacement ombragé confirmé.",                                    acquired_from=None,                    acquired_date=None,         grid_col=11, grid_row=8, grid_slot=1),
        dict(code="P42", common_name="Ajuga chocolate chip",         latin_name="Ajuga reptans 'Chocolate Chip'",          zone_code="right_border_back",  container="pleine terre",         status="Thriving",      status_notes="Acheté Carrefour 12.04.2026. Couvre-sol ombre — test zone difficile arrière bordure droite.",                        acquired_from="Carrefour Evere",       acquired_date="2026-04-12", grid_col=11, grid_row=8, grid_slot=1),

        # ── BACK ZONE / POND ──────────────────────────────────────────
        dict(code="P18", common_name="Jonc Spiralis",                latin_name="Juncus effusus spiralis",                 zone_code="pond",               container="pleine terre",         status="Thriving",      status_notes="OK.",                                                                                                                acquired_from=None,                    acquired_date=None,         grid_col=1,  grid_row=4, grid_slot=1),
        dict(code="P19", common_name="Pesse d'eau",                  latin_name="Hippuris vulgaris",                       zone_code="pond",               container="pot argile (fond)",    status="Struggling", status_notes="Étouffée par lentilles d'eau (Lemna minor).",                                                                        acquired_from=None,                    acquired_date=None,         grid_col=1,  grid_row=5, grid_slot=1),
    ]

    count = 0
    for p in plants:
        zone_code = p.pop("zone_code")
        zone_id = get_zone_id(session, zone_code)
        if zone_id is None:
            print(f"  ⚠️  Zone '{zone_code}' not found for {p['code']} — skipping")
            continue
        p["zone_id"] = zone_id
        session.execute(text("""
            INSERT INTO plants (
                code, common_name, latin_name, zone_id, container,
                status, status_notes, acquired_from, acquired_date,
                grid_col, grid_row, grid_slot, is_active
            ) VALUES (
                :code, :common_name, :latin_name, :zone_id, :container,
                :status, :status_notes, :acquired_from, :acquired_date,
                :grid_col, :grid_row, :grid_slot, TRUE
            )
            ON CONFLICT (code) DO NOTHING
        """), p)
        count += 1

    print(f"✓ {count} plants seeded")

if __name__ == "__main__":
    with Session(engine) as session:
        seed_plants(session)
        session.commit()
        print("\n✅ Plants seeded successfully")